### ISSUE TITLE
Changing variable out_features do not change the last Linear layer

### ISSUE THREAD

**Issue by gordinmitya** [tjmoon0104/pytorch-tiny-imagenet#3]
Hello and thank you for your example!
As your repository gets more popular I think it's important to say there's a typo in the code. For instance in file `ResNet18_64.ipynb`
![image](https://user-images.githubusercontent.com/9286092/95597898-e8da8680-0a57-11eb-91d5-cc504a1d20b4.png)
this only changes variable in Linear instance but do not change the actual output size.
You have to recreate this layer, as shown in
https://pytorch.org/tutorials/beginner/finetuning_torchvision_models_tutorial.html#resnet

#2 must be related to that

**Comment by tjmoon0104** [comment]
Updated to re-initialize the layer.
